### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by etczrn** [xoeye/gps-metadata-remover#23]
Hello, do you have a plan for supporting TypeScript? I desperately want that feature.

**Comment by Aleclindner** [comment]
This should be a pretty easy conversion, I can get to it soon.

**Comment by tycrek** [comment]
Any update on this?

**Comment by tycrek** [comment]
I wrote this for my own codebase, works well enough for me. Not sure how it would be adapted for publishing though.

`gps-metadata-remover.d.ts`
```ts
type ReadFunction = (size: number, offset: number) => Promise<Buffer>
type WriteFunction = (writeValue: string, entryOffset: number, encoding: string) => Promise<void>
type Options = {
	skipXMPRemoval?: boolean
}

declare module '@xoi/gps-metadata-remover' {
	export async function removeLocation(photoUri: string, read: ReadFunction, write: WriteFunction, options: Options = {}): Promise<boolean>
	export async function arrayBufferToBase64(buffer: ArrayBuffer): string
	export async function base64StringToArrayBuffer(base64String: string): Promise<Buffer>
}

```

**Comment by Aleclindner** [comment]
I'll check this out this week and do a release if it looks good.

**Comment by danielxoi** [comment]
This should be resolved in the latest release https://github.com/xoeye/gps-metadata-remover/releases/tag/v2.0.0
