### ISSUE TITLE
ffprobe should be a devDependency?

### ISSUE THREAD

**Issue by dominik-dabrowski** [xoeye/gps-metadata-remover#25]
If my reading of the source code is correct, `ffprobe` is only used for testing. If so, shouldn't it be in `devDependencies`? I implemented the change in https://github.com/substackinc/gps-metadata-remover/commit/18ea2bc24920c9b9561bfd481307260737697af5 :)

**Comment by Aleclindner** [comment]
Good catch, thanks :)

**Comment by Aleclindner** [comment]
Fixed
