### ISSUE TITLE
Frontend-friendly 

### ISSUE THREAD

**Issue by forresto** [xoeye/gps-metadata-remover#8]
> Frontend-friendly Javascript package that removes GPS metadata from images and videos

Based on this, are there examples of using this on the frontend?

**Comment by Aleclindner** [comment]
What's your use case? There's an example in the readme for how you might use it with react native.

**Comment by forresto** [comment]
The use case is protecting our users sensitive information, like GPS coordinates, by stripping it before it gets to our server. Would need a server-side version for API uploads though.

There are libraries that can read and write JPEG metadata on the frontend. It's possible, I just haven't found it.

**Comment by prmichaelsen** [comment]
@forresto did you manage to solve this issue?
